on:
  push:
    branches:
      - main

jobs:
  push-module:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v2

      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1

      # Push module to the BSR
      - uses: bufbuild/buf-push-action@v1
        with:
          input: proto/audit
          buf_token: ${{ secrets.BUF_TOKEN }}
          draft: ${{ github.ref_name != 'main' }}
